name: NCSC CSAF Harvester

on:
  schedule:
    - cron: "0 * * * 1-5"
    - cron: "55 21 * * 6,0"
    - cron: "55 22 * * 6,0"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ncsc-csaf-harvester-${{ github.ref }}
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: self-hosted

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Weekend 23:55 Europe/Amsterdam gate
        run: |
          DOW=$(TZ=Europe/Amsterdam date +%u)
          HM=$(TZ=Europe/Amsterdam date +%H:%M)
          if [ "$DOW" -ge 6 ] && [ "$HM" != "23:55" ]; then
            echo "Weekend en lokale tijd is $HM, niet 23:55 — job wordt overgeslagen."
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run scraper (met dedupe en Telegram)
        run: python scraper.py

      - name: Commit & push outputs/state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/sent_cache.json output/last_run.json output/daily/*.csv 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated NCSC advisories update"
            git pull --rebase --autostash
            git push || true
          fi
