name: NCSC CSAF Harvester

on:
  schedule:
    # Doordeweeks (ma-vr) elk uur om xx:00 UTC
    - cron: "0 * * * 1-5"
    # Weekend runs die samen 23:55 NL-tijd afdekken (CET/CEST)
    - cron: "55 21 * * 6,0"  # dekkend voor CEST (UTC+2)
    - cron: "55 22 * * 6,0"  # dekkend voor CET (UTC+1)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ncsc-csaf-harvester
  cancel-in-progress: false

jobs:
  harvest:
    runs-on: self-hosted
    steps:
      # Gate: alleen in het weekend precies 23:55 lokale tijd draaien.
      # Door deze stap kun je veilig twee weekend-crons hebben zonder dubbele runs.
      - name: Weekend 23:55 Europe/Amsterdam gate
        run: |
          DOW=$(TZ=Europe/Amsterdam date +%u)   # 1=maandag ... 7=zondag
          HM=$(TZ=Europe/Amsterdam date +%H:%M)
          if [ "$DOW" -ge 6 ]; then
            if [ "$HM" != "23:55" ]; then
              echo "Weekend en lokale tijd is $HM, niet 23:55 — job wordt overgeslagen."
              exit 0
            fi
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # nodig voor rebase
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install feedparser
          fi

      - name: Run scraper
        run: python scraper.py

      # Optioneel: Telegram notificatie bij nieuwe advisories
      - name: (Optional) Notify Telegram if new advisories
        if: ${{ env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != '' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          NEW_COUNT=$(jq -r '.new_count' output/last_run.json 2>/dev/null || echo "")
          if [ -n "$NEW_COUNT" ] && [ "$NEW_COUNT" != "0" ]; then
            MSG="NCSC harvester: ${NEW_COUNT} nieuwe advisories."
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" \
              -d text="$MSG" || true
          fi

      - name: Commit & push outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage alles wat veranderd is door de run
          git add -A

          # Commit alleen als er staged changes zijn
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "NCSC advisories update [skip ci]"
          git pull --rebase --autostash
          git push
