name: NCSC Advisories Daily

on:
  schedule:
    - cron: "0 6 * * *"   # elke dag 06:00 UTC ≈ 08:00 NL (zomertijd)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Daily NCSC advisories" || echo "No changes to commit"
          git push
