name: NCSC Advisories Frequent

on:
  schedule:
    - cron: "*/60 * * * *"   # elke 10 min (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ncsc-scraper
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "NCSC advisories update [skip ci]" || echo "No changes to commit"
          git push || true

      - name: Read last_run.json
        id: last
        run: |
          python - << 'PY'
          import json
          data = json.load(open('output/last_run.json', encoding='utf-8'))
          print(f"new_count={data.get('new_count',0)}")
          print(f"csv_path={data.get('csv_path','')}")
          PY >> $GITHUB_OUTPUT

      - name: Send Telegram message
        if: steps.last.outputs.new_count != '0'
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MSG="NCSC update: ${{ steps.last.outputs.new_count }} nieuwe adviezen.\nCSV: ${{ steps.last.outputs.csv_path }}"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$MSG"

      - name: Send Telegram CSV
        if: steps.last.outputs.new_count != '0'
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          FILE="${{ steps.last.outputs.csv_path }}"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
            -F chat_id="${CHAT_ID}" \
            -F document=@"${FILE}" \
            -F caption="Dagelijkse NCSC CSV: ${FILE}"
